inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
  - 'omniauth-casport.gemspec'
  - 'lib/omniauth/casport/version.rb'
  - 'spec/**/*'
  - 'vendor/cache/**/*'
  - 'vendor/bundle/**/*'
  - '**/gems/**/*'
  - 'omniauth-dice.gemspec'
